// <auto-generated />
using GameModels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameModels.Migrations
{
    [DbContext(typeof(APIContext))]
    partial class APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameModels.Models.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://tombraiders.net/stella/images/timeline/tomb_raider_1_box.jpg",
                            Name = "Tomb Raider",
                            ReleaseDate = "1996"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://tombraiders.net/stella/images/timeline/tomb_raider_2_box.jpg",
                            Name = "Tomb Raider 2",
                            ReleaseDate = "1997"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://tombraiders.net/stella/images/timeline/tomb_raider_3_box.jpg",
                            Name = "Tomb Raider 3",
                            ReleaseDate = "1998"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://tombraiders.net/stella/images/timeline/tomb_raider_4_box.jpg",
                            Name = "Tomb Raider The Last Revelation",
                            ReleaseDate = "1999"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
